plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'signing'
}

group = 'name.jurgenei.gradle'
version = '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.12.2'
}

gradlePlugin {
    plugins {
        archiPlugin {
            id = 'name.jurgenei.gradle.archi'
            implementationClass = 'name.jurgenei.gradle.archi.ArchiGradlePlugin'
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom {
                name = 'Archi Plugin'
                description = 'Gradle plugin for Archi architecture description'
                url = 'https://github.com/jurgenei/gradle-archi-plugin'

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'jurgenei'
                        name = 'Jurgen Hildebrand'
                    }
                }

                scm {
                    connection = 'scm:git:https://github.com/jurgenei/gradle-archi-plugin.git'
                    developerConnection = 'scm:git:ssh://git@github.com/jurgenei/gradle-archi-plugin.git'
                    url = 'https://github.com/jurgenei/gradle-archi-plugin'
                }
            }
        }
    }

    repositories {
        mavenLocal()
    }
}

signing {
    required { gradle.taskGraph.hasTask("publish") }
    def signingKey = findProperty("signingKey")
    def signingPassword = findProperty("signingPassword")
    if (signingKey && signingPassword) {
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign publishing.publications.mavenJava
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

