name: CI
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
on:
  push:
    branches: ["main", "release/**"]
  pull_request:
    branches: ["main", "release/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: wrapper
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew --no-daemon clean build
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: test-results
          path: build/test-results/

